const HEARTBEAT = 'VIDEOWIKI_HEARTBEAT';
const RECORDED_AUDIO_PROCESSED = 'RECORDED_AUDIO_PROCESSED';
const AUTHENTICATE = 'AUTHENTICATE';
const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
const AUTHENTICATE_FAILED = 'AUTHENTICATE_FAILED';
const TRANSLATION_SUBSLIDE_CHANGE = 'TRANSLATION_SUBSLIDE_CHANGE';
const VIDEO_UPLOADED = 'VIDEO_UPLOADED';
const VIDEO_TRANSCRIBED = 'VIDEO_TRANSCRIBED';
const VIDEO_DONE = 'VIDEO_DONE';
const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
const EXTRACT_VIDEO_BACKGROUND_MUSIC_FINISH = 'EXTRACT_VIDEO_BACKGROUND_MUSIC_FINISH';
const NOISE_CANCELLATION_VIDEO_FINISH = `NOISE_CANCELLATION_VIDEO_FINISH`;
const AI_TRANSCRIBE_VIDEO_FINISH = `AI_TRANSCRIBE_VIDEO_FINISH`;
const AUTOMATIC_VIDEO_BREAKING_DONE = `AUTOMATIC_VIDEO_BREAKING_DONE`;

module.exports = {
    AUTHENTICATE,
    AUTHENTICATE_SUCCESS,
    AUTHENTICATE_FAILED,
    HEARTBEAT,
    RECORDED_AUDIO_PROCESSED,
    TRANSLATION_SUBSLIDE_CHANGE,
    VIDEO_UPLOADED,
    VIDEO_TRANSCRIBED,
    VIDEO_DONE,
    DOWNLOAD_FILE,
    NEW_NOTIFICATION,
    EXTRACT_VIDEO_BACKGROUND_MUSIC_FINISH,
    NOISE_CANCELLATION_VIDEO_FINISH,
    AI_TRANSCRIBE_VIDEO_FINISH,
    AUTOMATIC_VIDEO_BREAKING_DONE,
}